[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn wsgi:app --timeout 300"
healthcheckPath = "/health"
restartPolicyType = "on_failure"

[service]
name = "yayvd"
port = "8080"
